apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: k8s-inference-sim
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: inference-sim
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: k8s-inference-sim:local
      - op: replace
        path: /spec/replicas
        value: 1
